apiVersion: v1
kind: Secret
metadata:
  name: harbor-user
  namespace: nanjun
  annotations:
    tekton.dev/docker-0: http://registry.nanjun
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: zhounanjun
---
apiVersion: v1
kind: Secret
metadata:
  name: github-user
  namespace: nanjun
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: your_github_username
  password: your_github_password
