apiVersion: v1
kind: Secret
metadata:
  name: harbor-user
  namespace: nanjun
  annotations:
    tekton.dev/docker-0: http://registry.nanjun
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: zhounanjun
